[2025-05-07T07:05:39.773+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-07T07:05:39.793+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bottleneck_pipeline.upload_logs_final manual__2025-05-05T12:05:52.099826+00:00 [queued]>
[2025-05-07T07:05:39.799+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bottleneck_pipeline.upload_logs_final manual__2025-05-05T12:05:52.099826+00:00 [queued]>
[2025-05-07T07:05:39.800+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-05-07T07:05:39.810+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): upload_logs_final> on 2025-05-05 12:05:52.099826+00:00
[2025-05-07T07:05:39.814+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2025-05-07T07:05:39.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bottleneck_pipeline', 'upload_logs_final', 'manual__2025-05-05T12:05:52.099826+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/bottleneck_pipeline.py', '--cfg-path', '/tmp/tmpgs2cq27a']
[2025-05-07T07:05:39.819+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask upload_logs_final
[2025-05-07T07:05:39.832+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-05-07T07:05:39.864+0000] {task_command.py:426} INFO - Running <TaskInstance: bottleneck_pipeline.upload_logs_final manual__2025-05-05T12:05:52.099826+00:00 [running]> on host 81855855d86b
[2025-05-07T07:05:39.925+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bottleneck_pipeline' AIRFLOW_CTX_TASK_ID='upload_logs_final' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T12:05:52.099826+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T12:05:52.099826+00:00'
[2025-05-07T07:05:39.926+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-07T07:05:39.937+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-07T07:05:39.939+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/14_upload_all_logs.py']
[2025-05-07T07:05:39.946+0000] {subprocess.py:86} INFO - Output:
[2025-05-07T07:05:39.995+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/scripts/14_upload_all_logs.py': [Errno 2] No such file or directory
[2025-05-07T07:05:39.998+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-07T07:05:39.999+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-07T07:05:40.008+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-07T07:05:40.011+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=bottleneck_pipeline, task_id=upload_logs_final, execution_date=20250505T120552, start_date=20250507T070539, end_date=20250507T070540
[2025-05-07T07:05:40.021+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task upload_logs_final (Bash command failed. The command returned a non-zero exit code 2.; 64)
[2025-05-07T07:05:40.032+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-07T07:05:40.047+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-07T07:05:40.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
