[2025-05-07T07:07:40.528+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-07T07:07:40.551+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bottleneck_pipeline.upload_logs_final manual__2025-05-05T12:05:52.099826+00:00 [queued]>
[2025-05-07T07:07:40.562+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bottleneck_pipeline.upload_logs_final manual__2025-05-05T12:05:52.099826+00:00 [queued]>
[2025-05-07T07:07:40.563+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-05-07T07:07:40.573+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): upload_logs_final> on 2025-05-05 12:05:52.099826+00:00
[2025-05-07T07:07:40.578+0000] {standard_task_runner.py:63} INFO - Started process 67 to run task
[2025-05-07T07:07:40.580+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bottleneck_pipeline', 'upload_logs_final', 'manual__2025-05-05T12:05:52.099826+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/bottleneck_pipeline.py', '--cfg-path', '/tmp/tmpcnosz69x']
[2025-05-07T07:07:40.583+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask upload_logs_final
[2025-05-07T07:07:40.598+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-05-07T07:07:40.635+0000] {task_command.py:426} INFO - Running <TaskInstance: bottleneck_pipeline.upload_logs_final manual__2025-05-05T12:05:52.099826+00:00 [running]> on host 81855855d86b
[2025-05-07T07:07:40.701+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bottleneck_pipeline' AIRFLOW_CTX_TASK_ID='upload_logs_final' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T12:05:52.099826+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T12:05:52.099826+00:00'
[2025-05-07T07:07:40.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-07T07:07:40.713+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-07T07:07:40.714+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/14_upload_all_logs.py']
[2025-05-07T07:07:40.722+0000] {subprocess.py:86} INFO - Output:
[2025-05-07T07:07:40.772+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/scripts/14_upload_all_logs.py': [Errno 2] No such file or directory
[2025-05-07T07:07:40.775+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-07T07:07:40.776+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-07T07:07:40.785+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-07T07:07:40.788+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=bottleneck_pipeline, task_id=upload_logs_final, execution_date=20250505T120552, start_date=20250507T070740, end_date=20250507T070740
[2025-05-07T07:07:40.798+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task upload_logs_final (Bash command failed. The command returned a non-zero exit code 2.; 67)
[2025-05-07T07:07:40.844+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-07T07:07:40.858+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-07T07:07:40.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
